"""empty message

Revision ID: 6384640378ca
Revises: 
Create Date: 2025-07-21 19:28:43.390056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6384640378ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.add_column('messages', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_messages_message_id', table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'message_id')
    op.create_foreign_key(None, 'usertochat', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertochat', type_='foreignkey')
    op.add_column('messages', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index('ix_messages_message_id', 'messages', ['message_id'], unique=False)
    op.drop_column('messages', 'id')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
